### ISSUE TITLE
Add a dependency to Radical.Bootstrapper?

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#121]
We have this https://github.com/RadicalFx/Radical-Boostrappers and Radical has its own boostrapping process, that does a lot more that that.
But...why not extend https://github.com/RadicalFx/Radical-Boostrappers here to add support to what WPF and Universal Apps need?

**Comment by micdenny** [comment]
What is the purpose of [Radical-Bootstrappers](https://github.com/RadicalFx/Radical-Boostrappers)? It is a generic boostrapper that you can also use in console application for instance? Sorry if I ask this, but I've never used, and I need more details to reply this.

**Comment by mauroservienti** [comment]
Yes it is, it is a generic bootstrapper based on the same conventions model as the built-in Radical one

**Comment by micdenny** [comment]
So you are thinking to inherits from base [BootstrapConventions](https://github.com/RadicalFx/Radical-Boostrappers/blob/develop/src/net45/Radical.Bootstrapper/BootstrapConventions.cs) for example here on the Castle [BootstrapConventions](https://github.com/RadicalFx/radical/blob/develop/src/net40/Radical.Windows.Presentation.CastleWindsor/Boot/BootstrapConventions.cs), and inherits the same stuff like `IsConcreteType`, `IsService`, and so on... If yes, I think it could be nice, at the end is called `Radical-Bootstrappers` right? so it is supposed to be used in Radical packages, otherwise how you can trust such a unused package, eheheh :smile:

**Comment by mauroservienti** [comment]
:-) yes exactly something like that.

**Comment by mauroservienti** [comment]
This issue was moved to RadicalFx/Radical.Windows.Presentation#10
