### ISSUE TITLE
Problem with Interaction.Behaviors

### ISSUE THREAD

**Issue by danielearrighi** [RadicalFx/Radical#252]
Hello,
Please excuse me if this is not the place to ask for help but I cannot find any documentation about this:
In a Windows I have a `ItemsControl` with a simple button as a `DataTemplate`.
I'm trying to setup an Handle for the clicked event so here's the current XAML:

```
[...]
<ItemsControl.ItemTemplate>
    <DataTemplate>
        <Button Content="Click Me" CommandParameter="{Binding MyRowId}">
            <i:Interaction.Behaviors>
                <behaviors:Handle RoutedEvent="Button.Click" WithCommand="{Binding Path=DoSomethingWithMyRowId}" PassingIn="$args" />
            </i:Interaction.Behaviors>
        </Button>
    </DataTemplate>
</ItemsControl.ItemTemplate>
```

In the ViewModel, I understand I need to handle a simple Button Click event like:
```
private void DoSomethingWithMyRowId(object sender, RoutedEventArgs e)
{
       var clickedRowId = ((Button)e.Source).CommandParameter;;
}
```

If I click the button, the application just crashes without exceptions (Visual Studio goes in Break Mode).
What am I missing?

Thank you for your help!

**Comment by danielearrighi** [comment]
For compleness (just to be sure is not a Dll problem):
xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
(From Microsoft.Expression.Interaction Nuget Package)
xmlns:behaviors="http://schemas.topics.it/wpf/radical/windows/behaviors"

**Comment by mauroservienti** [comment]
Hi Daniele, thanks for reporting this. I’ll move this to the right venue and have a look.

**Comment by mauroservienti** [comment]
Here I am, sorry for the delay. Busy days with family.

The `Handle` behavior cannot be used in that way. It's very basic and at the moment works with `ICommand` only. In your scenario you must expose an `ICommand` implementation from the view model. Something like:

```
class MainViewModel : AbstractViewModel
{
    public class MyDataSource
    {
        public MyDataSource()
        {
            MyRowIdCommand = DelegateCommand.Create()
                .OnExecute(obj =>
                {

                });
        }

        public int MyRowId { get; set; }
        public ICommand MyRowIdCommand { get; }
    }

    public MainViewModel()
    {
        Data = new List<MyDataSource>
        {
            new MyDataSource{ MyRowId =1 },
            new MyDataSource{ MyRowId =2 }
        };
    }

    public IEnumerable<MyDataSource> Data { get; private set; }
}
```

the important thing to notice is that the command implementation is defined on the item that is bound to the `ItemTemplate` item. In your original markup:

```
<ItemsControl.ItemTemplate>
    <DataTemplate>
        <Button Content="Click Me" CommandParameter="{Binding MyRowId}">
            <i:Interaction.Behaviors>
                <behaviors:Handle RoutedEvent="Button.Click" WithCommand="{Binding Path=DoSomethingWithMyRowId}" PassingIn="$args" />
            </i:Interaction.Behaviors>
        </Button>
    </DataTemplate>
</ItemsControl.ItemTemplate>
```

due to the way WPF binding works the `DoSomethingWithMyRowId` thing is searched on the single item bound to the `ItemsTemplate`, thus it must be defined there and not on the main view model. Something like the following works with my above ViewModel sample:

```
<ItemsControl.ItemTemplate>
    <DataTemplate>
        <Button Content="Click Me" CommandParameter="{Binding MyRowId}">
            <i:Interaction.Behaviors>
                <behaviors:Handle RoutedEvent="Button.Click" WithCommand="{Binding Path=MyRowIdCommand}" PassingIn="$args" />
            </i:Interaction.Behaviors>
        </Button>
    </DataTemplate>
</ItemsControl.ItemTemplate>
```

At this point however you don't really need anymore the `Handle` behavior, that was originally designed for a different, and more subtle, use case. You can simply change your markup to:

```
<ItemsControl.ItemTemplate>
    <DataTemplate>
        <Button Content="Click Me" Command="{Binding path=MyRowIdCommand}" />
    </DataTemplate>
</ItemsControl.ItemTemplate>
```

the `MyDataSource` holds the row id for you.

**Comment by mauroservienti** [comment]
@danielearrighi I’ll close this as fixed. Do not hesitate to reopen it if you’re still facing issues.
